spring.application.name=Recruitment-Solution

server.port = 9090





spring.data.mongodb.uri=mongodb+srv://pradeeptha:pradeeptha123@cluster0.gr4v8.mongodb.net/testdb?retryWrites=true&w=majority&appName=Cluster0


openai.api.key=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


